{% set name = "lalframe" %}
{% set version = "3.0.1" %}

# dependencies
{% set lal_version = "7.3.0" %}
{% set framecpp_version = "2.5.5,<3.0.0a0" %}
{% set framel_version = "8.39.2,<9.0.0a0" %}
{% set swig_version = "3.0.10" %}

package:
  name: {{ name }}-split
  version: {{ version }}

source:
  url: https://software.igwn.org/sources/source/lalsuite/{{ name }}-{{ version }}.tar.xz
  sha256: 18bfef4618b48f784cd8ba58d3cf10d2cdaa29b94e0951ba927f22d8e2243fca

build:
  error_overdepending: true
  error_overlinking: true
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - help2man >=1.37
    - make
    - pkg-config
    - swig >={{ swig_version }}
  host:
    - ldas-tools-framecpp >={{ framecpp_version }}
    - libframel >={{ framel_version }}
    - liblal >={{ lal_version }}

outputs:
  - name: liblalframe
    script: install-lib.sh
    build:
      run_exports:
        - {{ pin_subpackage("liblalframe", max_pin="x") }}
    requirements:
      build:
        - {{ compiler('c') }}
        - make  # [not win]
        - swig >={{ swig_version }}
      host:
        - ldas-tools-framecpp >={{ framecpp_version }}
        - libframel >={{ framel_version }}
        - liblal >={{ lal_version }}
      run:
        - ldas-tools-framecpp >={{ framecpp_version }}
        - libframel >={{ framel_version }}
        - liblal >={{ lal_version }}
      run_constrained:
        - lalframe >=1.5.3
        - python-lalframe >=1.5.3
    test:
      requires:
        - pkg-config
      commands:
        # check library
        - test -f ${PREFIX}/lib/liblalframe${SHLIB_EXT}  # [unix]
        # check pkg-config
        - pkg-config --print-errors --exact-version "${PKG_VERSION}" lalframe
    about:
      home: https://wiki.ligo.org/Computing/LALSuite
      doc_url: https://lscsoft.docs.ligo.org/lalsuite/lalframe/
      dev_url: https://git.ligo.org/lscsoft/lalsuite.git
      license: GPL-2.0-or-later
      license_family: GPL
      license_file: COPYING
      summary: LSC Algorithm Frame Library shared object libraries
      description: |
        The LSC Algorithm Frame Library for gravitational wave data analysis.
        This package contains the shared-object libraries needed to run
        applications that use the LAL Frame library.

  - name: python-lalframe
    script: build-python.sh
    build:
      error_overdepending: true
      error_overlinking: true
      ignore_run_exports:
        - numpy
        - python
    requirements:
      build:
        - {{ compiler('c') }}
        - help2man >=1.37
        - make
        - pkg-config
        - swig >={{ swig_version }}
        # extras for cross compiling with python
        - python                              # [build_platform != target_platform]
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
        - numpy                               # [build_platform != target_platform]
      host:
        - {{ pin_subpackage('liblalframe', exact=True) }}
        - numpy
        - python
      run:
        - {{ pin_subpackage('liblalframe', exact=True) }}
        - {{ pin_compatible('numpy') }}
        - python
        - python-lal >={{ lal_version }}
    test:
      imports:
        - lalframe
        - lalframe.frread
      requires:
        - pytest >=4.0.0a0
      source_files:
        - test/python
        - test/F-TEST-*.gwf
      commands:
        - python -m pytest -ra -v test/python
    about:
      home: https://wiki.ligo.org/Computing/LALSuite
      doc_url: https://lscsoft.docs.ligo.org/lalsuite/lalframe/
      dev_url: https://git.ligo.org/lscsoft/lalsuite.git
      license: GPL-2.0-or-later
      license_family: GPL
      license_file: COPYING
      summary: LSC Algorithm Frame Library
      description: |
        The LSC Algorithm Frame Library for gravitational wave data analysis.
        This package contains the Python bindings of the LALFrame C libraries
        and additional Python modules.

        Note: this package only provides the importable Python libraries.
        All command-line interfaces, scripts, and executables are
        part of the `lalframe` package.

  - name: lalframe
    script: install-bin.sh
    build:
      ignore_run_exports:
        - python
    requirements:
      build:
        - {{ compiler('c') }}
        - help2man >=1.37
        - make
        - sed
      host:
        - liblal >={{ lal_version }}
        - {{ pin_subpackage('liblalframe', exact=True) }}
        - python
      run:
        - liblal >={{ lal_version }}
        - {{ pin_subpackage('liblalframe', exact=True) }}
        - python
        - {{ pin_subpackage('python-lalframe', exact=True) }}
    test:
      source_files:
        - test/F-TEST-600000000-60.gwf
      imports:
        - lalframe
      commands:
        - lalframe_version --verbose
        - lalfr-cksum test/F-TEST-600000000-60.gwf
        - lalfr-cut H1:LSC-AS_Q test/F-TEST-600000000-60.gwf > /dev/null
        - lalfr-dump test/F-TEST-600000000-60.gwf
        - lalfr-paste test/F-TEST-600000000-60.gwf > /dev/null
        - lalfr-split test/F-TEST-600000000-60.gwf
        - lalfr-stat test/F-TEST-600000000-60.gwf
        - lalfr-stream --channel H1:LSC-AS_Q --start-time 600000000 --duration 0.01 --frame-glob test/F-TEST-*.gwf
        - lalfr-vis --channel H1:LSC-AS_Q --start-time 600000000 --duration 0.01 --frame-glob test/F-TEST-*.gwf
    about:
      home: https://wiki.ligo.org/Computing/LALSuite
      doc_url: https://lscsoft.docs.ligo.org/lalsuite/lalframe/
      dev_url: https://git.ligo.org/lscsoft/lalsuite.git
      license: GPL-2.0-or-later
      license_family: GPL
      license_file: COPYING
      summary: LSC Algorithm Frame Library
      description: |
        The LSC Algorithm Frame Library for gravitational wave data analysis.
        This package contains the runtime tools.

about:
  home: https://wiki.ligo.org/Computing/LALSuite
  doc_url: https://lscsoft.docs.ligo.org/lalsuite/lalframe/
  dev_url: https://git.ligo.org/lscsoft/lalsuite.git
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: LSC Algorithm Frame Library
  description: |
    The LSC Algorithm Frame Library for gravitational wave data analysis.

extra:
  feedstock-name: lalframe
  recipe-maintainers:
    - duncanmmacleod
    - skymoo
