{% set name = "lalframe" %}
{% set version = "1.4.4" %}
{% set sha256 = "518016915e4189fabf2a247ebe227eb8733afc4a1daa6e7ae6b30a1d87c61707" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.xz
  url: http://software.ligo.org/lscsoft/source/lalsuite/{{ name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  number: 1002
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - pkg-config
    - swig >=3.0.7
  host:
    - gsl
    - lal >=6.19.0
    - libframe
    - ldas-tools-framecpp >=2.5.5
  run:
    - gsl
    - lal
    - ldas-tools-framecpp >=2.5.5
    - libframe

test:
  commands:
    - lalframe_version --verbose
    - lalfr-vis --help

outputs:
  - name: lalframe
    build:
      run_exports:
        - {{ pin_subpackage("lalframe", max_pin="x.x") }}

  - name: python-lalframe
    script: install-python.sh
    build:
      activate_in_script: True
    requirements:
      build:
        - {{ compiler('c') }}
        - make
        - pkg-config
        - swig >=3.0.7
      host:
        - {{ pin_subpackage('lalframe', exact=True) }}
        - numpy
        - python
      run:
        - {{ pin_subpackage('lalframe', exact=True) }}
        - {{ pin_compatible('numpy') }}
        - python
        - python-lal >=6.19.0
    test:
      imports:
        - lalframe
        - lalframe.frread
    about:
      home: https://wiki.ligo.org/Computing/DASWG/LALSuite
      doc_url: https://lscsoft.docs.ligo.org/lalsuite/lalframe/
      dev_url: https://git.ligo.org/lscsoft/lalsuite/
      license: GPLv3
      license_family: GPL
      license_file: COPYING
      summary: LSC Algorithm Frame Library
      description: |
        The LSC Algorithm Frame Library for gravitational wave data analysis.
        This package contains the python bindings.

about:
  home: https://wiki.ligo.org/Computing/DASWG/LALSuite
  doc_url: https://docs.ligo.org/lscsoft/lalsuite/lalframe/
  dev_url: https://git.ligo.org/lscsoft/lalsuite/
  license: GPLv3
  license_family: GPL
  license_file: COPYING
  summary: LSC Algorithm Frame Library
  description: |
    The LSC Algorithm Frame Library for gravitational wave data analysis.
    This package contains the shared-object libraries needed to run
    applications that use the LAL Frame library.  If you want to install
    the Python bindings, please install the associated python-lalframe
    package.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - skymoo
