{% set name = "lalframe" %}
{% set version = "1.5.3" %}
{% set sha256 = "d0300611e706d5ca09b85ed00b4714d671a1d67a429714b5618bce4dae042de6" %}

# dependencies
{% set lal_version = "7.1.0" %}
{% set framecpp_version = "2.5.5" %}
{% set framel_version = "8.39.2" %}
{% set swig_version = "3.0.10" %}

package:
  name: {{ name }}-split
  version: {{ version }}

source:
  url: http://software.ligo.org/lscsoft/source/lalsuite/{{ name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  error_overdepending: true
  error_overlinking: true
  number: 2
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - help2man >=1.37
    - make
    - pkg-config
    - swig >={{ swig_version }}
  host:
    - ldas-tools-framecpp >={{ framecpp_version }}
    - libframel >={{ framel_version }}
    - liblal >={{ lal_version }}

outputs:
  - name: liblalframe
    script: install-lib.sh
    build:
      run_exports:
        - {{ pin_subpackage("liblalframe", max_pin="x") }}
    requirements:
      build:
        - {{ compiler('c') }}
        - make  # [not win]
        - swig >={{ swig_version }}
      host:
        - ldas-tools-framecpp >={{ framecpp_version }}
        - libframel >={{ framel_version }}
        - liblal >={{ lal_version }}
      run:
        - ldas-tools-framecpp >={{ framecpp_version }}
        - libframel >={{ framel_version }}
        - liblal >={{ lal_version }}
      run_constrained:
        - lalframe >=1.5.3
        - python-lalframe >=1.5.3
    test:
      requires:
        - pkg-config
      commands:
        - test $(pkg-config --modversion --print-errors lalframe) == "${PKG_VERSION}"
    about:
      home: https://wiki.ligo.org/Computing/LALSuite
      doc_url: https://lscsoft.docs.ligo.org/lalsuite/lalframe/
      dev_url: https://git.ligo.org/lscsoft/lalsuite/
      license: GPL-2.0-or-later
      license_family: GPL
      license_file: COPYING
      summary: LSC Algorithm Frame Library shared object libraries
      description: |
        The LSC Algorithm Frame Library for gravitational wave data analysis.
        This package contains the shared-object libraries needed to run
        applications that use the LAL Frame library.

  - name: python-lalframe
    script: install-python.sh
    build:
      error_overdepending: true
      error_overlinking: true
      ignore_run_exports:
        # ignore run_exports from python's recipe
        - python
    requirements:
      build:
        - {{ compiler('c') }}
        - make
        - pkg-config
        - swig >={{ swig_version }}
      host:
        - {{ pin_subpackage('liblalframe', exact=True) }}
        - numpy
        - python
      run:
        - {{ pin_subpackage('liblalframe', exact=True) }}
        - {{ pin_compatible('numpy') }}
        - python
        - python-lal >={{ lal_version }}
    test:
      imports:
        - lalframe
        - lalframe.frread
      requires:
        - pytest >=4.0.0a0
      source_files:
        - test/python
        - test/F-TEST-*.gwf
      commands:
        - python -m pytest -rs -v test/python
    about:
      home: https://wiki.ligo.org/Computing/LALSuite
      doc_url: https://lscsoft.docs.ligo.org/lalsuite/lalframe/
      dev_url: https://git.ligo.org/lscsoft/lalsuite/
      license: GPL-2.0-or-later
      license_family: GPL
      license_file: COPYING
      summary: LSC Algorithm Frame Library
      description: |
        The LSC Algorithm Frame Library for gravitational wave data analysis.
        This package contains the python bindings.

  - name: lalframe
    script: install-bin.sh
    build:
      ignore_run_exports:
        - python
    requirements:
      build:
        - {{ compiler('c') }}
        - make
      host:
        - liblal >={{ lal_version }}
        - {{ pin_subpackage('liblalframe', exact=True) }}
        - python
      run:
        - liblal >={{ lal_version }}
        - {{ pin_subpackage('liblalframe', exact=True) }}
        - python
        - {{ pin_subpackage('python-lalframe', exact=True) }}
    test:
      source_files:
        - test/F-TEST-600000000-60.gwf
      imports:
        - lalframe
      commands:
        - lalframe_version --verbose
        - lalfr-cksum test/F-TEST-600000000-60.gwf
        - lalfr-cut H1:LSC-AS_Q test/F-TEST-600000000-60.gwf > /dev/null
        - lalfr-dump test/F-TEST-600000000-60.gwf
        - lalfr-paste test/F-TEST-600000000-60.gwf > /dev/null
        - lalfr-split test/F-TEST-600000000-60.gwf
        - lalfr-stat test/F-TEST-600000000-60.gwf
        - lalfr-stream --channel H1:LSC-AS_Q --start-time 600000000 --duration 0.01 --frame-glob test/F-TEST-*.gwf
        - lalfr-vis --channel H1:LSC-AS_Q --start-time 600000000 --duration 0.01 --frame-glob test/F-TEST-*.gwf
    about:
      home: https://wiki.ligo.org/Computing/LALSuite
      doc_url: https://lscsoft.docs.ligo.org/lalsuite/lalframe/
      dev_url: https://git.ligo.org/lscsoft/lalsuite/
      license: GPL-2.0-or-later
      license_family: GPL
      license_file: COPYING
      summary: LSC Algorithm Frame Library
      description: |
        The LSC Algorithm Frame Library for gravitational wave data analysis.
        This package contains the runtime tools.

about:
  home: https://wiki.ligo.org/Computing/LALSuite
  doc_url: https://lscsoft.docs.ligo.org/lalsuite/lalframe/
  dev_url: https://git.ligo.org/lscsoft/lalsuite/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: LSC Algorithm Frame Library
  description: |
    The LSC Algorithm Frame Library for gravitational wave data analysis.

extra:
  feedstock-name: lalframe
  recipe-maintainers:
    - duncanmmacleod
    - skymoo
