appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: IizXsX5czAnSg24sIwCsIAXr7GxaGf4rEAsw/HRuofmZk9RL+RqPkWQcfXz3gJzZLc8XmGtK69OJYL/NaSe7O+C8HNXQlI+PLAG/0ez2w8hS9/yWAL4OCXA5fAPWiGAjbdDexuN1fazoIfMQKh3GKJVSYnNWVHbxOnqeg0xd/WtLE1PBmpUO7g9Hivs/O8lIgQnjnGs/ywJERiqvZ6i+yzLpK2uyCDHEIvhIKK9BblZTZl8XEWzl3jgBT5mpaf8A2np3MWrVD0R9jNKhPPfQKEK9R5DPsgPuMdmtFotYygjFjAXYDg859/0XxDff4cnSpRhh2lB9wEqLA3BDmaYyL7EAe0+/s9gnYg9D2MzR8vCTVTQ3nbCrsVuBL3x45bt4KWPk5VAcgXPnzyi93iXznrU9lh9lUSrT04u4pG5iXkibH+rMdAk07rGx8W/E68W1T86bSDy+EQrX3lkkLVYeYQCPKHCI1TDFqRuvmWSXDyYBxG9ZyqSnLKF000SxaZFvtGKsBKLfL8DJlj2HnxBDY6WYbgkEnGA41nDXJhpV5z+i+murkePqPabCxNb8uaOomaAUo4Xwvs5mDDFLoQOr4BwUGFPZ789hpAsfIxsLqV6PHJpLgJIIMFBnyMAtOXhdXM7zt6FCj7o0DvQpxFJut/+EyyDeF6qfrHDfrDPwwlA=}
conda_forge_output_validation: true
